const personality = [
  "Mentiroso(a)",
  "Mandão/Mandona",
  "Teimoso(a)",
  "Medroso(a)",
  "Brigão/Brigona",
  "'Maria vai com as outras'",
  "Subserviente",
  "Intrometido(a)",
  "Calado(a)",
  "Explosivo(a)",
  "Destemido(a)",
  "Falador(a)",
  "Caladão",
  "Curioso(a)",
  "Burro(a)",
  "Arrogante",
  "Pessimista",
  "Otimista",
  "Ingênuo(a)",
  "Temeroso(a)",
  "Temerário(a)",
  "Cordial",
  "Grudento(a)",
  "Confiante",
  "Rude",
  "Grosseiro(a)",
  "Delicado(a)",
  "Polido(a)",
  "Desengonçado(a)",
  "Pacato(a)"
]

export default personality