const physicalTrait = [
  "Gordo(a)",
  "Franzino(a)",
  "Atlético(a)",
  "Alto(a)",
  "Baixinho(a)",
  "Esguio",
  "Gigante",
  "Pernas longas",
  "Pernas curtas",
  "Pernas fortes",
  "Pernas finas, dois palitinhos",
  "Pernas bem torneadas",
  "Barriga de pochete",
  "Barriga bem definida",
  "Barriga saliente",
  "Barriga de batráquio",
  "Careca",
  "Cabeleira desgrenhada",
  "Cabeleira bagunçada",
  "Cabeleira cheia de nós",
  "Cabeleira parece um ninho de pássaros",
  "Cabelo escuro bem penteadinho",
  "Cabelo escuro de trancinhas",
  "Cabelo escuro bastante comprido",
  "Cabelo escuro encaracolado",
  "Cabelo escuro ondulado",
  "Cabelo loiro bem penteadinho",
  "Cabelo loiro de trancinhas",
  "Cabelo loiro bastante comprido",
  "Cabelo loiro encaracolado",
  "Cabelo loiro ondulado",
  "Cabelo ruivo bem penteadinho",
  "Cabelo ruivo de trancinhas",
  "Cabelo ruivo bastante comprido",
  "Cabelo ruivo encaracolado",
  "Cabelo ruivo ondulado",
  "Cabelo castanho bem penteadinho",
  "Cabelo castanho de trancinhas",
  "Cabelo castanho bastante comprido",
  "Cabelo castanho encaracolado",
  "Cabelo castanho ondulado",
  "Cabelo negro bem penteadinho",
  "Cabelo negro de trancinhas",
  "Cabelo negro bastante comprido",
  "Cabelo negro encaracolado",
  "Cabelo negro ondulado",
  "Usa um belo topete",
  "Usa um cabelo que cai sobre os olhos",
  "Cabelo caído sobre o rosto",
  "Cabelo de tigela",
  "Esquelético(a)",
  "Ombros largos",
  "Ombros grandes",
  "Ombros fortes",
  "Ombros estreitos",
  "Cabelo Ensebado",
  "Braços fortes",
  "Braços bem torneados",
  "Braços atléticos",
  "Braços compridos",
  "Braços finos",
  "Anca Larga",
  "Cabelos Claros",
  "Cabelos Ruivo",
  "Cabelos Castanhos",
  "Cabelos Negros",
  "Cabelos Escuros",
  "Cabelos Brancos",
  "Cabelos Grisalhos",
  "Cabelo bem curto",
  "Cabelo alinhado",
  "Cabelo sedoso",
  "Sobrancelhas fininhas",
  "Sobrancelhas grossas",
  "Sobrancelhas juntas",
  "Sobrancelhas estilo taturana"
]

export default physicalTrait