const quirk = [
  "Sua fácil!",
  "Conhece os negócios escusos de uma cidade longínqua!",
  "Conhece os negócios escusos de uma cidade vizinha!",
  "Conhece os negócios lucrativos de uma cidade longínqua!",
  "Conhece os negócios lucrativos de uma cidade vizinha!",
  "Usa uma capa vermelha.",
  "Usa uma capa preta.",
  "Usa uma capa azul.",
  "Usa uma capa marrom.",
  "Usa uma capa laranja.",
  "Usa uma capa verde.",
  "Usa uma capa branca.",
  "Usa uma capa amarela.",
  "As roupas estão sujas de lama!",
  "As roupas estão sujas de barro!",
  "As roupas estão sujas de feno!",
  "As roupas estão sujas de sangue!",
  "Olhar atento!",
  "Olhar confiante!",
  "Parece doente!",
  "Parece pálido!",
  "Está sempre tossindo!",
  "Não tem um dedinho!",
  "Tem uma mancha de nascimento escondida!",
  "Tem uma mancha de nascimento nas costas!",
  "Tem uma mancha de nascimento nas nádegas!",
  "Tem uma mancha de nascimento nas na perna!",
  "Tem uma mancha de nascimento nas no braço!",
  "Tem um olho de vidro assustador!",
  "Tem um olho de vidro guardado em seu bolso!",
  "Não para de coçar os olhos",
  "Fala espremendo os olhos",
  "Tem um bafo horrível!",
  "Tem um bafo álcool!",
  "Tem um bafo de menta!",
  "Tem um bafo doce!",
  "Está cheirando a álcool",
  "Está cheirando a suor",
  "Está cheirando a menta",
  "Está cheirando a flores",
  "Está cheirando a perfume!",
  "Suas botas são ótimas para lama!",
  "Suas botas são ótimas para o frio, têm pelos dentro!",
  "Suas botas são ótimas para escaladas, têm alguns cravos na sola!",
  "Tem uma voz rouca!",
  "Tem uma voz aveludada!",
  "Tem uma voz limpa!",
  "Tem uma voz forte!",
  "Suas mãos são bastante fortes!",
  "Suas mãos são bastante delicadas!",
  "Suas mãos são bastante grandes!",
  "Suas mãos são bastante pequenas!",
  "Anda de maneira engraçada!",
  "Anda de maneira confiante!",
  "Tem algumas cicatrizes pelo corpo!",
  "Conhece um latoeiro!",
  "Tem uma boa flexibilidade!",
  "Prende bem a respiração!",
  "Tem contatos com a nobreza!",
  "Tem contatos com o sindicato!",
  "Tem contatos uma caravana de mercadores!",
  "Tem contatos com um vendedor de cavalos!",
  "Tem contatos com um vendedor de espadas",
  "Tem contatos com um vendedor de porcos!",
  "Tem contatos com um vendedor de carvão!",
  "Tem contatos com um mago!",
  "Come muito!",
  "Tem muita sede!",
  "Usa um belo chapéu!",
  "Usa um tapa olho!",
  "Usa um cachecol!",
  "Usa um casaco!",
  "Usa um colar da família!",
  "É órfão!",
  "Tem 2 irmãos!",
  "Tem 3 irmãos!",
  "Tem 4 irmãos!",
  "Tem 5 irmãos!",
  "Tem 6 irmãos!",
  "Deve um favor á um soldado!",
  "Deve um favor á um mercador!",
  "Deve um favor á m amigo distante!",
  "Deve um favor á um familiar!",
  "Diz para todos que é abençoado por um Deus local!",
  "Diz para todos que é abençoado por um alinhamento de planetas!",
  "Diz para todos que é abençoado por umas fadinhas!",
  "Diz para todos que é abençoado por um fanático religioso!",
  "Tem trajes bem cortados, dignos de um nobre!",
  "{Ligeiramente atraente!",
  "Bastante atraente!",
  "Bem afeiçoado!",
  "Trabalhou numa taverna",
  "Trabalhou num estábulo",
  "Trabalhou num porto",
  "Trabalhou numa construção",
  "Trabalhou num navio}",
  "Gosta de cantar",
  "Toca um instrumento",
  "Sabe amolar uma espada",
  "Sabe dançar",
]

export default quirk